name: mass-rebuild
on: 
  # schedule: 
  #   - cron: '0 0 1 * *'
  workflow_dispatch:
  
jobs:
  lap_1:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
    strategy:
      matrix:
        pkg: [lame, fdk-aac, x264, x265, shotwell, foliate, alacritty, kitty, yofi]
    steps:
      - name: Building a package
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          curl -LO https://raw.githubusercontent.com/clearfraction/mass-rebuild/main/rebuild-package.sh && chmod +x ./rebuild-package.sh
          ./rebuild-package.sh ${{ matrix.pkg }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: /tmp/repository/*.rpm

  zed:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
    steps:
      - name: Building a package
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          curl -LO https://raw.githubusercontent.com/clearfraction/mass-rebuild/main/rebuild-package.sh && chmod +x ./rebuild-package.sh
          ./rebuild-package.sh zed
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: zed
          path: /tmp/repository/*.rpm

  vscodium:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
    steps:
      - name: Building a package
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          curl -LO https://github.com/clearfraction/vscodium/raw/main/build.sh && chmod +x ./build.sh
          sed -i '/^export CFLAGS=.*/ s/\ "/ -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3\ "/' build.sh
          sed -i '/^export CXXFLAGS=.*/ s/\ "/ -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3\ "/' build.sh
          sed -i '/^export FFLAGS=.*/ s/\ "/ -march=x86-64-v3 -m64-Wl,-z,x86-64-v3\ "/' build.sh
          sed -i '/^export FCFLAGS=.*/ s/\ "/ -march=x86-64-v3 -m64\ "/' build.sh
          sed -i '/^export LDFLAGS=.*/ s/\ "/ -march=x86-64-v3 -m64\ "/' build.sh
          sed -i '/^export RUSTFLAGS=.*/ s/-C target-cpu=westmere/-C target-cpu=haswell/' build.sh
          sed -i '/^export RUSTFLAGS=.*/ s/-C target-feature=+avx/-C target-feature=+avx,+avx2,+fma/' build.sh
          ./build.sh
          mv /home/RPMS /tmp/repository
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: vscodium
          path: /tmp/repository/*.rpm

  lap_2:
    needs: lap_1
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
    strategy:
      matrix:
        pkg: [ffmpeg, ffmpeg-cuda, kanshi, wlsunset, wl-clipboard, wlr-randr, swayblur, swww, autotiling, imv, nvidia-vaapi-driver, vdpau-va-driver-vp9, rio, sniffnet]
    steps:
      - name: Download result
        uses: actions/download-artifact@v4
        with:
          path: /tmp/repository
      - name: Building a package
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          curl -LO https://raw.githubusercontent.com/clearfraction/mass-rebuild/main/rebuild-package.sh && chmod +x ./rebuild-package.sh
          ./rebuild-package.sh ${{ matrix.pkg }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: /tmp/repository/*.rpm

  lap_3:
    needs: lap_2
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
    strategy:
      matrix:
        pkg: [wob, mpv, mpv-cuda, yt-dlp, gstreamer-libav, wf-recorder, grim, playerctl, brightnessctl, mako, webapp-manager, qt6ct, kvantum, keyd, youtube-tui, cloak, yazi, xdg-desktop-portal-termfilechooser, zellij]
    steps:
      - name: Download result
        uses: actions/download-artifact@v4
        with:
          path: /tmp/repository
      - name: Building a package
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          curl -LO https://raw.githubusercontent.com/clearfraction/mass-rebuild/main/rebuild-package.sh && chmod +x ./rebuild-package.sh
          ./rebuild-package.sh ${{ matrix.pkg }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: /tmp/repository/*.rpm

  finish:
    needs: [lap_3, vscodium, zed]
    runs-on: ubuntu-latest
    steps:
      - name: CD trigger
        shell: bash
        run: curl -i -u paulcarroty:$BUNDLES_TOKEN -X POST -H "Accept:application/vnd.github.v3+json" -d '{"event_type":"build"}' https://api.github.com/repos/clearfraction/bundles/dispatches; curl -i -u paulcarroty:$BUNDLES_TOKEN -X POST -H "Accept:application/vnd.github.v3+json" -d '{"event_type":"build"}' https://api.github.com/repos/clearfraction/mass-rebuild-v2/dispatches
        env:
          BUNDLES_TOKEN: ${{ secrets.BUNDLES_TOKEN }}
